FROM node:18
# adding your app.js file from your local directory into the / directory in the image, with the same name(app.js).
ADD app.js /app.js
# defining what command should be executed when image is run.
ENTRYPOINT ["node", "app.js"]