apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: skyliu01/kubia
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          exec:
            command:  # The readiness probe will periodically perform the command ls /var/ready inside the container.
            - ls
            - /var/ready