apiVersion: v1
kind: ReplicationController    # This manifest defines a ReplicationController
metadata:
  name: kubia                  # The name of this ReplicationController
spec:
  replicas: 3                  # The desired number of pod instances 
  selector:
    app: kubia                 # The pod selector determining what pods the RC is operating on
  template:                    # The pod template for creating new pods
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: skyliu01/kubia
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080