apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
  - image: luksa/kubia-unhealthy
    name: kubia
    livenessProbe:      # A liveness probe that will perform an HTTP GET
      httpGet:
        path: /
        port: 8080