apiVersion: v1
kind: Pod
metadata:
  name: loop-pod-secret
spec:
  containers:
  - image: skyliu01/loop-args
    name: loop-args
    env:
    - name: SECRET_1
      valueFrom:
        secretKeyRef:             # The variable should be set from the entry of a Secret.
          name: test.secret
          key: SECRET_1
    - name: SECRET_2
      valueFrom:
        secretKeyRef:         
          name: test.secret
          key: SECRET_2
    volumeMounts:
    - name: certs
      mountPath: /root     
  volumes:
  - name: certs
    secret:              
      secretName: test.secret     # You define the secret volume here, referring to the test.secret Secret.
