apiVersion: v1
kind: Pod
metadata:
  name: loop-args-config-map
spec:
  containers:
  - image: skyliu01/loop-args
    name: loop-args
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: loop-config
          key: sleep-interval
    args: ["$(INTERVAL)"]      # Referencing the environment variable in the argument